ALTER TABLE users
ADD COLUMN first_name VARCHAR(255) AFTER username,
ADD COLUMN last_name VARCHAR(255) AFTER first_name,
ADD COLUMN role INT NOT NULL DEFAULT 0 AFTER email,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER role,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
